a<-c(1,2,4,3,NA,5,9)
library(testthat)
library(stringr)
context("Remove_missing")
test_that("Remove_missing",{expect_equal(length(a),6)
  expect_false(anyNA(remove_missing(a)
  ))
  expect_equal(length(remove_missing(a)),5)
  expect_true(anyNA(a)
  )}
  
context("score_quiz")
test_that("score_quiz", {quizzes<-c(100,80,70,0)
          b<-c(19,20,14,17,16)
        expect_equal(score_quiz(quizzes, drop=TRUE),83+1/3)
        expect_equal(score_quiz(quizzes,drop=FALSE),62.5)
        expect_equal(score_quiz(b, drop=TRUE),18)
        expect_equal(score_quiz(b,drop=FALSE),17.2)
        })
context("score_lab")
test_that("score_lab",{
  expect_equal(score_lab(12),100)
  expect_equal(score_lab(6),0)
  expect_equal(score_lab(7),20)
  expect_equal(score_lab(8),40)
  })
